name: "Update Nix dependencies"

on:
  schedule:
    # Run on the 3rd of every month at 04:04
    # This should avoid spikes in usage caused by other scheduled jobs
    - cron: "4 4 3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          diagnostic-endpoint: ""
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - run: nix build -A packages.lon
      - env:
          LON_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LON_LABELS: "lon,bot"
          LON_LIST_COMMITS: 10
        run: ./result/bin/lon -vv bot github

env:
  FORCE_COLOR: 1
